name: junta192
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.1
  http: ^0.13.1
  curved_navigation_bar: ^0.3.7
  qr_flutter: ^4.0.0
  barcode_scan: ^3.0.1
  audioplayers: ^0.18.1
  image_picker: ^0.7.3
  timeline_list: ^0.0.5
  percent_indicator: ^3.0.1
  charts_flutter: ^0.10.0
  google_sign_in: ^5.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_facebook_login: ^3.0.0
  adaptive_action_sheet: ^2.0.0 
  url_launcher: ^6.0.3
  whatsapp_unilink: ^1.0.0+1
  google_mobile_ads: ^0.12.1
  auto_size_text: ^2.1.0
  share: ^2.0.1
  sign_in_with_apple: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

#  Inclusão do icone do Junta10
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-1024x1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/apple-logo-24x24.png
    - assets/images/no-user.png
    - assets/images/qrcode.png
    - assets/images/dart-flutter.jpg
    - assets/images/full-bloom.png
    - assets/images/mountains.jpeg
    - assets/images/mountains.jpg
    - assets/images/junta10-logo.png
    - assets/images/facebook.png
    - assets/images/presente.png
    - assets/images/notify-03.png
    - assets/images/youtube.png
    - assets/images/youtube-01.png
    - assets/images/money.png
    - assets/images/junta10-1000x1000.png
    - assets/images/logo-1024x1024.png
    - assets/images/sem-imagem.jpeg
    - assets/images/ajuda/presente.png
    - assets/images/ajuda/step-0.png
    - assets/images/ajuda/step-1.png
    - assets/images/ajuda/step-2.png
    - assets/images/ajuda/step-3.png
    - assets/images/ajuda/step-4.png
    - assets/images/ajuda/step-5.png
    - assets/images/ajuda/step-6.png
    - assets/images/ajuda/step-7.png
    - assets/images/ajuda/step-8.png
    - assets/images/ajuda/liberar-carimbo-0504211519.png
    - assets/images/ajuda/liberar-carimbo-finalizado-050420211521.png
    - assets/images/ajuda/liberar-novo-carimbo-050420211520.png
    - assets/images/ajuda/vendedor-fem-qrcode.png
    - assets/images/ajuda/bem-vindo.png
    - assets/images/ajuda/check-star.png
    - assets/images/ajuda/consumidor.png
    - assets/images/ajuda/readqrcode.png
    - assets/images/ajuda/cliente-faz-pedido.png
    - assets/images/ajuda/cliente-olha-cartao-registrado.png
    - assets/images/ajuda/motoboy-vai.png
    - assets/images/ajuda/motoboy-volta.png
    - assets/images/ajuda/sobre.png
    - assets/images/ajuda/bem-vindo-criar-carimbo.png
    - assets/images/ajuda/meus-cartoes-resgate.png
    - assets/images/ajuda/ajuda-btn-resgate.png
    - assets/images/ajuda/ajuda-codigo-resgate.png
    - assets/images/ajuda/ajuda-avaliar-campanha.png
    - assets/images/ajuda/ajuda-avaliar-campanha-conclusao.png
    - assets/images/ajuda/ajuda-entregar-recompensa.png
    - assets/images/ajuda/ajuda-validar-cartao.png
    - assets/images/ajuda/ajuda-codigo-validado-sucesso.png
    - assets/images/ajuda/ajuda-entregar-recompesa.png
    - assets/sounds/cash-register.mp3
    - assets/config/global-startup.json

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf

